apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proxy-sm
  labels:
    release: prom  
spec:
  endpoints:
  - interval: 30s
    path: '/swagger-stats/metrics'
    port: nginx
    scheme: http
  selector:
    matchLabels:
      app: nginx
