FROM grafana/grafana:10.1.4
COPY yesoreyeram-infinity-datasource /var/lib/grafana/plugins/yesoreyeram-infinity-datasource 
# RUN sudo grafana-cli plugins install yesoreyeram-infinity-datasource 
# RUN chown -R grafana:grafana /var/lib/grafana/plugins/yesoreyeram-infinity-datasource
