---
# Source: grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  labels:
    helm.sh/chart: grafana-8.3.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: my-grafana
    app.kubernetes.io/version: "11.1.0"
    app.kubernetes.io/managed-by: Helm
  name: my-grafana
  namespace: monitoring
---
# Source: grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-8.3.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: my-grafana
    app.kubernetes.io/version: "11.1.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  
  admin-user: "YWRtaW4="
  admin-password: "VWJWSERvVFEwSm1BVW4yWndIUHRWd3lBTEppNlRSYWV3VFR3elVNZg=="
  ldap-toml: ""
---
# Source: grafana/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    helm.sh/chart: grafana-8.3.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: my-grafana
    app.kubernetes.io/version: "11.1.0"
    app.kubernetes.io/managed-by: Helm
  name: my-grafana-clusterrole
rules: []
---
# Source: grafana/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-grafana-clusterrolebinding
  labels:
    helm.sh/chart: grafana-8.3.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: my-grafana
    app.kubernetes.io/version: "11.1.0"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: my-grafana
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: my-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
# Source: grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-8.3.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: my-grafana
    app.kubernetes.io/version: "11.1.0"
    app.kubernetes.io/managed-by: Helm
rules: []
---
# Source: grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-8.3.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: my-grafana
    app.kubernetes.io/version: "11.1.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-grafana
subjects:
- kind: ServiceAccount
  name: my-grafana
  namespace: monitoring
---
# # Source: grafana/templates/service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-grafana-grafana
#   namespace: monitoring
#   labels:
#     helm.sh/chart: grafana-8.3.2
#     app.kubernetes.io/name: grafana
#     app.kubernetes.io/instance: my-grafana
#     app.kubernetes.io/version: "11.1.0"
#     app.kubernetes.io/managed-by: Helm
# spec:
#   type: NodePort
#   ports:
#     - name: service
#       port: 80
#       protocol: TCP
#       targetPort: 3000
#       nodePort: 8003
#   selector:
#     app.kubernetes.io/name: grafana
#     app.kubernetes.io/instance: my-grafana