apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.23.0
  name: alertmanager-main
  namespace: monitoring
type: Opaque  
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 2m
    
    route:
      receiver: alert-emailer
      group_by: ['...']
      routes:
        - receiver: alertsnitch
          continue: true

        - receiver: alert-emailer
          # Send severity=email alerts to email.
          match:
            apps: web-apps           
          repeat_interval: 1m 

        - receiver: 'null'
          # Suppress severity=none|info alerts.
          match_re:
            severity: none|info                 

    receivers:
    - name: alertsnitch
      webhook_configs:
        - url: http://alertsnitch.monitoring.svc.cluster.local:5432/webhook

    - name: 'null'
    - name: alert-emailer
      email_configs:
      - to: gkumarsun@gmail.com        
        from: gkumarsun@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: gkumarsun@gmail.com
        auth_identity: gkumarsun@gmail.com
        auth_password: "ADD-PASSWORD"
        #severity: '{{ range .Alerts }}{{ if eq .Labels.severity "critical"}}P1{{else if eq .Labels.severity "warning"}}P2{{else if eq .Labels.severity "info"}}P3{{else}}P4{{end}}{{end}}'
        require_tls: true
        send_resolved: true   
        headers:
          subject: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.severity }} - {{.CommonLabels.alertname}} - {{.CommonLabels.namespace}}'
        html: |
          Hi {{ .GroupLabels.email_to }}, 

          <p>
          You have the following firing alerts.
          <ul>
          {{ range .Alerts }}
          <li>Severity={{ .Labels.severity }} for {{.Labels.alertname}} on {{ .Annotations.description }} <br></li>
          {{ end }}
          </ul>
          </p>



