apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.23.0
  name: alertmanager-main
  namespace: monitoring
type: Opaque  
stringData:
  alertmanager.yaml: |-
    global:
    templates:
    - '/etc/alertmanager/config/*.tmpl' 
    
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      routes:
        - receiver: slack_demo
        # Send severity=info|warning alerts to slack.
          match_re:
            severity: info|warning|critical
          group_wait: 10s
          repeat_interval: 1m
        - receiver: alert-emailer
        # Send severity=email alerts to email.
          match:
            severity: email
          group_wait: 10s
          repeat_interval: 1m          

    receivers:
    - name: alert-emailer
      email_configs:
      - to: gkumarsun@gmail.com        
        from: gkumarsun@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: gkumarsun@gmail.com
        auth_identity: gkumarsun@gmail.com
        auth_password: hgeyfmexptpjcerk
        require_tls: true
        send_resolved: true   
        headers:
          subject: "You have {{ .Alerts.Firing | len }} firing alerts"
        html: |
          Hi {{ .GroupLabels.email_to }},

          <p>
          You have the following firing alerts:
          <ul>
          {{ range .Alerts }}
          <li>{{.Labels.alertname}} on {{ .Annotations.description }}</li>
          {{ end }}
          </ul>
          </p>

    - name: slack_demo
      slack_configs:
      - api_url: <>
        send_resolved: true      
        channel: '#alertsmanager'
        title: '{{ template "slack.my.title" . }}'
        text: '{{ template "slack.my.text" . }}'    
        # text: "{{ range .Alerts }}**[{{ .Status }}]** {{ .Annotations.summary }}\n{{ .Annotations.description }}\n\n{{ end }}"
       
  slack.tmpl: |
    {{ define "slack.my.title" -}}
        {{- if .CommonAnnotations.summary -}}
            {{- .CommonAnnotations.summary -}}
        {{- else -}}
            {{- with index .Alerts 0 -}}
                {{- .Annotations.summary -}}
            {{- end -}}
        {{- end -}}
    {{- end }}
    {{ define "slack.my.text" -}}
        {{- if .CommonAnnotations.description -}}
            {{- .CommonAnnotations.description -}}
        {{- else -}}
            {{- range $i, $alert := .Alerts }}
                {{- "\n" -}} {{- .Annotations.description -}}
            {{- end -}}
        {{- end -}}
    {{- end }}
  email.tmpl: |    

