apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.23.0
  name: alertmanager-main
  namespace: monitoring
type: Opaque  
stringData:
  alertmanager.yaml: |-
    global:
    templates:
      - '/etc/alertmanager/config/*.tmpl'    
    route:
      receiver: Default
      routes:
        - receiver: alertsnitch
          continue: true

        - receiver: warning-alerts-notify
          group_by: [namespace]  
          matchers:        
          - apps=web-apps
          - severity="Warning"
          - priority="P4"
          repeat_interval: 1m 

        - receiver: critical-alerts-notify
          group_by: ['...']        
          matchers:
          - apps=web-apps
          - severity=~"Critical|Minor|Major"
          - priority=~"P1|P2|P3"        
          repeat_interval: 1m 

        - receiver: 'null'
          # Suppress severity=none|info alerts.
          match_re:
            severity: none|info                 

    receivers:
    - name: alertsnitch
      webhook_configs:
        - url: http://alertsnitch.monitoring.svc.cluster.local:5432/webhook

    - name: 'null'
    - name: Default
    
    - name: warning-alerts-notify
      email_configs:
      - to: anamika.ritu11@gmail.com        
        from: anamika.ritu11@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: anamika.ritu11@gmail.com
        auth_identity: anamika.ritu11@gmail.com
        auth_password: "ADD-PASSWORD"        
        require_tls: true
        send_resolved: true   
        headers:
          subject: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.severity }} {{ .CommonLabels.priority }} | {{.CommonLabels.alertname}} | {{.CommonLabels.namespace}}'
        html: '{{ template "custom_email_warning.tmpl" . }}' 

    - name: critical-alerts-notify
      email_configs:
      - to: anamika.ritu11@gmail.com        
        from: anamika.ritu11@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: anamika.ritu11@gmail.com
        auth_identity: anamika.ritu11@gmail.com
        auth_password: "ADD-PASSWORD"        
        require_tls: true
        send_resolved: true   
        headers:
          subject: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.severity }} {{ .CommonLabels.priority }} | {{.CommonLabels.alertname}} | {{.CommonLabels.namespace}}'
        html: '{{ template "custom_email_critical.tmpl" . }}'


  custom_email_warning.tmpl: |-
          <h2 style="color:blue">{{ .Alerts.Firing | len }} Warning Alerts</h2>          
          {{ range .Alerts }}
          <p>
          <b>{{.Labels.alertname}} at Timestamp = {{.StartsAt}}</b>
            <ul>{{ range .Labels.SortedPairs }}
            <li>{{ .Name }} = {{ .Value }}</li>
            {{ end }}</ul>
            <ul>{{ range .Annotations.SortedPairs }}
            <li>{{ .Name }} = {{ .Value }}</li>
            {{ end }}</ul>            
          </p>
          {{ end }}  

  custom_email_critical.tmpl: |-
          <h2 style="color:red">{{ .Alerts.Firing | len }} Warning Alerts</h2>          
          {{ range .Alerts }}
          <p>
          <b>{{.Labels.alertname}} at Timestamp = {{.StartsAt}}</b>
            <ul>{{ range .Labels.SortedPairs }}
            <li>{{ .Name }} = {{ .Value }}</li>
            {{ end }}</ul>
            <ul>{{ range .Annotations.SortedPairs }}
            <li>{{ .Name }} = {{ .Value }}</li>
            {{ end }}</ul>            
          </p>
          {{ end }}  
