apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.23.0
  name: alertmanager-main
  namespace: monitoring
type: Opaque  
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 2m    
    route:
      receiver: alert-emailer      
      routes:
        - receiver: alertsnitch
          continue: true

        - receiver: alert-emailer
          group_by: ['...']
          match:
            apps: web-apps           
          repeat_interval: 1m 

        - receiver: 'null'
          # Suppress severity=none|info alerts.
          match_re:
            severity: none|info                 

    receivers:
    - name: alertsnitch
      webhook_configs:
        - url: http://alertsnitch.monitoring.svc.cluster.local:5432/webhook

    - name: 'null'
    - name: alert-emailer
      email_configs:
      - to: anamika.ritu11@gmail.com        
        from: anamika.ritu11@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: anamika.ritu11@gmail.com
        auth_identity: anamika.ritu11@gmail.com
        auth_password: "ADD-PASSWORD"        
        require_tls: true
        send_resolved: true   
        headers:
          subject: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.severity }} {{ .CommonLabels.priority }} | {{.CommonLabels.alertname}} | {{.CommonLabels.namespace}}'
        html: |-
          <h3>You have the following alerts:</h3>
          {{ range .Alerts }}
          <p>
          <b>{{.Labels.alertname}} at Timestamp = {{.StartsAt}}</b>

            <ul>{{ range .Labels.SortedPairs }}
            <li>{{ .Name }} = {{ .Value }}</li>
            {{ end }}</ul>

            <ul>{{ range .Annotations.SortedPairs }}
            <li>{{ .Name }} = {{ .Value }}</li>
            {{ end }}</ul>            
          </p>
          {{ end }}



