apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
  name: app-prometheus-rules
spec:
  groups:
  - name: Infra-Performance
    rules:
    - alert: ContainerCPUPercentageUsage_critical  
      expr: |
        ((sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits) by (pod)) * 100 >= 0)      
      for: 0m
      labels:
        apps: web-apps
        severity: Critical
        priority: P1
      annotations:
        description: "Container {{ $labels.pod }} has high CPU usage VALUE = {{ $value }} %"
        summary: "High CPU usage by Container {{ $labels.pod }} based on CPU Resource Limits"  

    - alert: ContainerMemoryPercentageUsage_critical  
      expr: |
        (sum(container_memory_working_set_bytes{job="kubelet", metrics_path="/metrics/cadvisor",container!="", image!=""}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits) by (pod)  * 100 < 90)
      for: 0m
      labels:
        apps: web-apps
        severity: Critical
        priority: P1
      annotations:
        description: "Container {{ $labels.pod }} has high Memory usage VALUE = {{ $value }} %"
        summary: "High Memory usage by Container {{ $labels.pod }} based on Memory Resource Limits" 

    # This rule can be very noisy in dynamic infra with legitimate container start/stop/deployment.
    - alert: ContainerKilled
      expr: time() - container_last_seen{namespace!~"kube-public|kube-system|default|monitoring"} > 10
      for: 0m
      labels:
        apps: web-apps
        severity: Warning   
        priority: P4
      annotations:
        summary: Container killed (instance {{ $labels.instance }})
        description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}" 

    - alert: 404 Error-micro-app
      expr: http_server_requests_seconds_count{exception="None",method="GET",outcome="CLIENT_ERROR",status="404",uri="/**",} > 0
      for: 0m
      labels:
        apps: web-apps
        severity: Minor
        priority: P3   
      annotations:
        summary: 404 Error Hello-world Service  (instance {{ $labels.instance }})
        description: "Hello-world Service not available\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: NodejsCPUUsageHigh
      expr: nodejs_process_cpu_usage_percentage > 0.10
      for: 0m
      labels:
        apps: web-apps
        severity: Minor
        priority: P3       
      annotations:
        summary: NodeJS CPU Usage is high (instance {{ $labels.instance }})
        description: "NodeJS CPU Usage is high\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: MethodResponseTime
      expr: greeting_time_seconds{class="com.tutorialworks.demos.springbootwithmetrics.GreetingController",exception="none",method="greeting",quantile="0.5",} > 0
      for: 0m
      labels:
        apps: web-apps
        severity: Warning
        priority: P4      
      annotations:
        summary: Method greeting response is high (instance {{ $labels.instance }})
        description: "Method greeting response is high\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}" 

    - alert: KubernetesPodCrashLooping
      expr: increase(kube_pod_container_status_restarts_total[10m]) > 0
      for: 0m
      labels:
        apps: web-apps
        severity: Warning
        priority: P4
      annotations:
        timestamp: >
          time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}         
        summary: Kubernetes pod crash looping (instance {{ $labels.instance }})      
        description: "Pod {{ $labels.pod }} is crash looping\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: KubernetesPodNotHealthy
      expr: min_over_time(sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"})[3m:1s]) > 0
      for: 0m      
      labels:
        apps: web-apps
        severity: Warning
        priority: P4
      annotations:
        timestamp: >
          time: {{ with query "time()" }}{{ . | first | value | humanizeTimestamp }}{{ end }}      
        summary: Kubernetes Pod not healthy (instance {{ $labels.instance }})
        description: "Pod has been in a non-ready state. \n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: KubernetesReplicassetMismatch
      expr: kube_replicaset_spec_replicas != kube_replicaset_status_ready_replicas
      for: 0m
      labels:
        apps: web-apps
        severity: Major
        priority: P2
      annotations:
        summary: Kubernetes ReplicasSet mismatch (instance {{ $labels.instance }})
        runbook_url: https://confluence-datacenter.du.ae/display/DevOps/Runbook+for+Pod+status+alerts+-+CRP#RunbookforPodstatusalertsCRP-KubernetesReplicassetMismatch
        description: "Deployment Replicas mismatch\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: KubernetesDeploymentReplicasMismatch
      expr: kube_deployment_spec_replicas != kube_deployment_status_replicas_available
      for: 0m
      labels:
        apps: web-apps
        severity: Critical
        priority: P1
      annotations:
        summary: Kubernetes Deployment replicas mismatch (instance {{ $labels.instance }})
        runbook_url: https://confluence-datacenter.du.ae/display/DevOps/Runbook+for+Pod+status+alerts+-+CRP#RunbookforPodstatusalertsCRP-KubernetesDeploymentReplicasMismatch
        description: "Deployment Replicas mismatch\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: KubernetesStatefulsetReplicasMismatch
      expr: kube_statefulset_status_replicas_ready != kube_statefulset_status_replicas
      for: 0m
      labels:
        apps: web-apps
        severity: Warning
        priority: P4
      annotations:
        summary: Kubernetes StatefulSet replicas mismatch (instance {{ $labels.instance }})
        runbook_url: https://confluence-datacenter.du.ae/display/DevOps/Runbook+for+Pod+status+alerts+-+CRP#RunbookforPodstatusalertsCRP-KubernetesStatefulsetReplicasMismatch
        description: "A StatefulSet does not match the expected number of replicas.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"   