# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-micrometer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
      # annotations:
      #   prometheus.io/scrape: 'true'
      #   prometheus.io/port: '9404'
      #   prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
      - name: hello-app
        image: gauravkr19/helloworld-micro:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"    
                    
---
apiVersion: v1
kind: Service
metadata:
  name: hello-micro
  labels:
    app: micro  
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - port: 80
    name: micro
    targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: micro-sm
spec:
  endpoints:
  - interval: 30s
    path: /actuator/prometheus
    port: micro
    scheme: http
  selector:
    matchLabels:
      app: micro
