apiVersion: v1
kind: Service
metadata:
  name: comicbox-service
  labels:
    app: nodejs
spec:
  selector:
    app: comicbox
  type: LoadBalancer
  ports:
    - port: 3000
      name: nodejs
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comicbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comicbox
  template:
    metadata:
      labels:
        app: comicbox
      # annotations:
      #       prometheus.io/scrape: "true"
      #       prometheus.io/path: 'swagger-stats/metrics'
      #       prometheus.io/port: "3000"
    spec:
      containers:
        - name: comicbox
          image: gauravkr19/comicbox
          ports:
            - containerPort: 3000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-sm
spec:
  endpoints:
  - interval: 30s
    path: 'swagger-stats/metrics'
    port: nodejs
    scheme: http
  selector:
    matchLabels:
      app: nodejs            
