apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: blackbox
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        http:
          preferred_ip_protocol: "ip4"
          tls_config:
            insecure_skip_verify: true
      https_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: [ "HTTP/1.1", "HTTP/2" ]
          valid_status_codes: []
          method: GET
          preferred_ip_protocol: "ip4"
          tls_config:
            insecure_skip_verify: false

