apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: blackbox
  labels:
    app: blackbox-exporter
spec:
  ports:
    - port: 9115
      targetPort: 9115
      protocol: TCP
      name: http
  selector:
    app: blackbox-exporter
