apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: blackbox
  labels:
    app: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - name: blackbox-exporter
        image: quay.io/prometheus/blackbox-exporter:latest
        args:
          - '--config.file=/config/blackbox.yml'
        ports:
          - containerPort: 9115
            protocol: TCP
        volumeMounts:
          - name: config-volume
            mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: blackbox-exporter-config
