apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: otel-k8s
  namespace: opentelemetry-operator-system
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-k8s
rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    - nodes/metrics
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - ingresses   
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs:
    - get
    - list
    - watch
  - nonResourceURLs:
    - /metrics
    verbs:
    - get    
  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors 
    - podmonitors  
    verbs:
    - get
    - list
    - watch    
  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices  
    verbs:
    - get
    - list
    - watch  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-k8s
subjects:
- kind: ServiceAccount
  name: otel-k8s
  namespace: opentelemetry-operator-system


