apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: micro-sm
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: micro
    scheme: http
  selector:
    matchLabels:
      app: micro