apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: collector-with-ta
spec:
  mode: statefulset
  targetAllocator:
    enabled: true  
    serviceAccount: otel-k8s
    prometheusCR:
      enabled: true  
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
        #   - job_name: 'blackbox-exporter'
        # target_allocator:
        #   endpoint: http://blackbox-exporter
        #   interval: 30s
        #   collector_id: "${POD_NAME}"

        #   - job_name: 'vm-otel-collector'
        # target_allocator:
        #   endpoint: http://104.155.113.142:8888
        #   interval: 30s
        #   collector_id: "${POD_NAME}"

        #   - job_name: 'vm-otel-node'
        # target_allocator:
        #   endpoint: http://104.155.113.142:9200
        #   interval: 30s
        #   collector_id: "${POD_NAME}"

          - job_name: 'vm-otel-postgres'
        target_allocator:
          endpoint: http://104.155.113.142:9187
          interval: 30s
          collector_id: "${POD_NAME}"
              
    exporters:
      logging:

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [logging]