apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: micro-sm
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      app: micro
---
apiVersion: v1
kind: Service
metadata:
  name: vm-postgres
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 9187
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vm-postgres
subsets:
  - addresses:
      - ip: 104.155.113.142
    ports:
      - port: 9187
