apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vm-postgres-sm
  labels:
    app: postgres
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: vm-postgres
  labels:
    app: postgres  
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 9187
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vm-postgres
  labels:
    app: postgres  
subsets:
  - addresses:
      - ip: 104.199.79.234
    ports:
      - port: 9187
        name: http
