apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: collector-with-ta-prometheus-cr
  namespace: opentelemetry-operator-system
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: otel-k8s
    prometheusCR:
      enabled: true
  config: |
    receivers:
      prometheus:
        config:

    exporters:
      logging:

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [logging]