apiVersion: apps/v1
kind: Deployment
metadata:
  name: license-monitor
  namespace: app-mon
  labels:
    app: license-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: license-monitor
  template:
    metadata:
      labels:
        app: license-monitor
    spec:
      containers:
        - name: license-monitor
          image: docker.io/gauravkr19/license-monitor:v4
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /license_info.yaml
              subPath: license_info.yaml
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
      volumes:
        - name: config-volume
          configMap:
            name: license-info-config

