apiVersion: v1
kind: Service
metadata:
  labels:
    app: license-monitor
  name: license-monitor
  namespace: app-mon
spec:
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8000
    name: license
  selector:
    app: license-monitor
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: license-monitor
  name: license-monitor-sm
  namespace: app-mon
spec:
  endpoints:
  - interval: 30s
    port: http
    path: /metrics
  selector:
    matchLabels:
      app: license-monitor


