apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: my-grafana
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2024-07-11T05:45:29Z"
  labels:
    app.kubernetes.io/instance: my-grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.1.0
    helm.sh/chart: grafana-8.3.2
  name: my-grafana
  namespace: monitoring
  resourceVersion: "170778"
  uid: 3e236b3f-9486-46e9-a864-65270b005312
