apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [server]
    http_addr =
    http_port = 3000
    domain = ad93359e9b2c.mylabserver.com:8003
    root_url = https://ad93359e9b2c.mylabserver.com:8003
    cert_key = /etc/tls/tls.key
    cert_file = /etc/tls/tls.crt
    enforce_domain = False
    protocol = https

kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: my-grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.1.0
    helm.sh/chart: grafana-8.3.2
  name: my-grafana
  namespace: monitoring
