apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prom
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2022-05-06T07:52:14Z"
  labels:
    app.kubernetes.io/instance: prom
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 8.2.5
    helm.sh/chart: grafana-6.17.10
  name: prom-grafana
  namespace: monitoring
  resourceVersion: "2119934"
  uid: f550a68e-f559-4eee-9953-5d517ff57d67
spec:
  clusterIP: 10.97.61.250
  clusterIPs:
  - 10.97.61.250
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prom
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
